<template>
  <article class="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8">
    <header class="mb-8 space-y-3">
      <p class="text-xs font-semibold uppercase tracking-wider text-accent-600">Tool 2 · English Level Checker</p>
      <h1 class="text-3xl font-bold text-ink-900 sm:text-4xl">
        AI English Level Checker — estimate your CEFR range from your own writing
      </h1>
      <p class="text-base text-ink-700">
        Paste 100–500 words of your own writing. Get an estimated CEFR band
        (A1–C2), five sub-scores, three things to work on next, and a 7-day
        starter plan you can actually fit into a weekday.
      </p>
    </header>

    <ClientOnly>
      <LevelForm
        v-model="text"
        v-model:goal="goal"
        :status="status"
        :remaining-quota="remainingQuota"
        @submit="onSubmit"
      />
      <template #fallback>
        <div class="card h-64 animate-pulse rounded-2xl bg-paper-100" />
      </template>
    </ClientOnly>

    <div v-if="error" class="mt-6 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800" role="alert">
      {{ error }}
    </div>

    <div v-if="status === 'loading'" class="mt-8">
      <div class="card animate-pulse space-y-3">
        <div class="h-4 w-1/3 rounded bg-paper-200" />
        <div class="h-2 w-1/2 rounded bg-paper-200" />
        <div class="h-2 w-2/3 rounded bg-paper-200" />
      </div>
    </div>

    <div v-else-if="data" class="mt-10 space-y-6">
      <LevelResult :result="data.result" />
      <div class="card-flat flex flex-col items-start gap-3 sm:flex-row sm:items-center sm:justify-between">
        <p class="text-sm text-ink-700">
          Want a sentence-level naturalness scan on the same text?
        </p>
        <NuxtLink to="/english-naturalness-checker" class="btn-secondary">Try the Naturalness Checker</NuxtLink>
      </div>
    </div>

    <section class="prose-ink mt-12 max-w-none">
      <h2>What the CEFR estimate means</h2>
      <p>
        The <strong>Common European Framework of Reference</strong> (CEFR) describes six
        bands of language proficiency, from A1 (beginner) to C2 (proficient). Most
        everyday writing lives somewhere in the B1–B2 range. The estimate you see
        here is generated by the rule on weight of your sentence complexity, vocabulary
        diversity, and a small set of common patterns.
      </p>
      <p>
        We deliberately keep the output small and actionable. Instead of a long
        report you probably won't read, you get three concrete priorities and a
        week of short exercises — picked from the dimension where you scored lowest.
      </p>

      <h3>How to use it well</h3>
      <ul>
        <li>Paste something you wrote, not a textbook excerpt.</li>
        <li>Write 100–500 words. Shorter samples give a lower-confidence estimate.</li>
        <li>Pick the goal that matches why you care about your level — that changes which improvements we surface first.</li>
      </ul>

      <h3>What this tool is not</h3>
      <ul>
        <li>It is not an official CEFR, IELTS, TOEFL, PTE or Cambridge certification.</li>
        <li>It does not understand audio, only the writing in the sample you submitted.</li>
        <li>It is one signal. Use it together with teacher feedback, mock exam results, or the Naturalness Checker for a fuller picture.</li>
      </ul>
    </section>
  </article>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import type { LevelGoal } from '~/types/level'

const config = useRuntimeConfig()

const { status, error, data, remainingQuota, check } = useLevel()
const { send } = useAnalytics()

const text = ref('')
const goal = ref<LevelGoal>('general')

function onSubmit(submittedText: string, submittedGoal: LevelGoal) {
  check(submittedText, submittedGoal)
  send('tool_form_submit', { tool: 'level' })
}

useSeoMeta({
  title: 'AI English Level Checker — estimate your CEFR band (A1–C2)',
  description:
    'Paste 100–500 words of your own writing. Get an AI-assisted CEFR estimate (A1–C2), sub-scores, three priorities and a 7-day starter plan. Free, no signup.',
  ogTitle: 'AI English Level Checker — estimate your CEFR band',
  ogDescription:
    'Estimate your CEFR range from your own writing. Sub-scores, three priorities, a 7-day plan. Free, no signup.',
  ogImage: `${config.public.siteUrl}/og-image.svg`,
  ogUrl: `${config.public.siteUrl}/english-level-checker`,
  twitterTitle: 'AI English Level Checker',
  twitterDescription:
    'Estimate your CEFR range from your own writing. Sub-scores, three priorities, a 7-day plan.',
  twitterImage: `${config.public.siteUrl}/og-image.svg`,
  twitterCard: 'summary_large_image',
  canonical: `${config.public.siteUrl}/english-level-checker`,
})

useHead({
  link: [{ rel: 'canonical', href: `${config.public.siteUrl}/english-level-checker` }],
  script: [
    {
      type: 'application/ld+json',
      innerHTML: JSON.stringify({
        '@context': 'https://schema.org',
        '@type': 'WebApplication',
        name: 'AI English Level Checker',
        url: `${config.public.siteUrl}/english-level-checker`,
        applicationCategory: 'EducationalApplication',
        operatingSystem: 'Any',
        browserRequirements: 'Requires JavaScript',
        inLanguage: 'en',
        description:
          'Estimates a CEFR band from a 100–500 word writing sample and returns sub-scores, three priorities and a 7-day plan.',
        offers: {
          '@type': 'Offer',
          price: 0,
          priceCurrency: 'USD',
          availability: 'https://schema.org/InStock',
        },
        breadcrumb: {
          '@type': 'BreadcrumbList',
          itemListElement: [
            { '@type': 'ListItem', position: 1, name: 'Home', item: `${config.public.siteUrl}` },
            { '@type': 'ListItem', position: 2, name: 'English Level Checker', item: `${config.public.siteUrl}/english-level-checker` },
          ],
        },
      }),
    },
  ],
})

definePageMeta({
  title: 'AI English Level Checker',
})
</script>