<template>
  <article class="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8">
    <header class="mb-8 space-y-3">
      <p class="text-xs font-semibold uppercase tracking-wider text-accent-600">Tool 2 · English Level Checker</p>
      <h1 class="text-3xl font-bold text-ink-900 sm:text-4xl">
        AI English Level Checker — estimate your CEFR range from your own writing
      </h1>
      <p class="text-base text-ink-700">
        Paste 100–500 words of your own writing. Get an estimated CEFR band
        (A1–C2), five sub-scores, three things to work on next, and a 7-day
        starter plan you can actually fit into a weekday.
      </p>
    </header>

    <ClientOnly>
      <LevelForm
        v-model="text"
        v-model:goal="goal"
        :status="status"
        :remaining-quota="remainingQuota"
        @submit="onSubmit"
      />
      <template #fallback>
        <div class="card h-64 animate-pulse rounded-2xl bg-paper-100" />
      </template>
    </ClientOnly>

    <div v-if="error" class="mt-6 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800" role="alert">
      {{ error }}
    </div>

    <div v-if="status === 'loading'" class="mt-8">
      <div class="card animate-pulse space-y-3">
        <div class="h-4 w-1/3 rounded bg-paper-200" />
        <div class="h-2 w-1/2 rounded bg-paper-200" />
        <div class="h-2 w-2/3 rounded bg-paper-200" />
      </div>
    </div>

    <div v-else-if="data" class="mt-10 space-y-6">
      <LevelResult :result="data.result" />
      <div class="card-flat flex flex-col items-start gap-3 sm:flex-row sm:items-center sm:justify-between">
        <p class="text-sm text-ink-700">
          Want a sentence-level naturalness scan on the same text?
        </p>
        <NuxtLink to="/english-naturalness-checker" class="btn-secondary">Try the Naturalness Checker</NuxtLink>
      </div>
    </div>

    <section class="prose-ink mt-12 max-w-none">
      <h2>What the CEFR estimate means</h2>
      <p>
        The <strong>Common European Framework of Reference</strong> (CEFR) describes six
        bands of language proficiency, from A1 (beginner) to C2 (proficient). Most
        everyday writing lives somewhere in the B1–B2 range. The estimate you see
        here is generated by the rule on weight of your sentence complexity, vocabulary
        diversity, and a small set of common patterns.
      </p>
      <p>
        We deliberately keep the output small and actionable. Instead of a long
        report you probably won't read, you get three concrete priorities and a
        week of short exercises — picked from the dimension where you scored lowest.
      </p>

      <h3>How to use it well</h3>
      <ul>
        <li>Paste something you wrote, not a textbook excerpt.</li>
        <li>Write 100–500 words. Shorter samples give a lower-confidence estimate.</li>
        <li>Pick the goal that matches why you care about your level — that changes which improvements we surface first.</li>
      </ul>

      <h3>What this tool is not</h3>
      <ul>
        <li>It is not an official CEFR, IELTS, TOEFL, PTE or Cambridge certification.</li>
        <li>It does not understand audio, only the writing in the sample you submitted.</li>
        <li>It is one signal. Use it together with teacher feedback, mock exam results, or the Naturalness Checker for a fuller picture.</li>
      </ul>
    </section>

    <section class="prose-ink mt-12 max-w-none">
      <h2>How to check your English level with AI</h2>
      <p>
        This AI English level checker analyses your writing sample and estimates your CEFR range
        (A1–C2). Unlike a traditional English level test online free of charge but limited to
        multiple-choice questions, it looks at your actual sentence complexity, vocabulary diversity,
        grammar patterns, and coherence. That makes it a more realistic writing level checker than a
        fixed quiz.
      </p>
      <p>
        You can also use it as an English proficiency checker before registering for an official
        exam, or as a quick way to check my English level AI-style before a job application,
        internship, or course enrolment.
      </p>
    </section>

    <section class="prose-ink mt-12 max-w-none">
      <h2>From level estimate to English study plan</h2>
      <p>
        Once you know your estimated level, the next question is usually: <em>what should I study
        next?</em> The result includes three priorities and a 7-day starter plan. If you want a
        longer roadmap, the same input can be the starting point for an English study plan
        generator: pick a target level (for example B2), set the time you have each day, and get a
        personalised English learning plan generator output with weekly milestones.
      </p>
      <p>
        This approach works as a language learning plan generator for self-study learners, and as an
        English learning schedule generator for anyone who wants structure without committing to a
        full course.
      </p>
    </section>

    <section class="prose-ink mt-12 max-w-none">
      <h2>Frequently asked questions</h2>
      <div class="mt-4 divide-y divide-ink-200 rounded-2xl border border-ink-200 bg-white not-prose">
        <details v-for="faq in faqs" :key="faq.q" class="group p-5 sm:p-6">
          <summary class="flex cursor-pointer items-center justify-between gap-4 text-base font-semibold text-ink-900">
            {{ faq.q }}
            <svg viewBox="0 0 24 24" class="h-4 w-4 text-ink-400 transition group-open:rotate-180" fill="none" stroke="currentColor" stroke-width="2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6 9l6 6 6-6" />
            </svg>
          </summary>
          <p class="mt-3 text-sm leading-relaxed text-ink-700">{{ faq.a }}</p>
        </details>
      </div>
    </section>
  </article>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import type { LevelGoal } from '~/types/level'

const config = useRuntimeConfig()

const { status, error, data, remainingQuota, check } = useLevel()
const { send } = useAnalytics()

const text = ref('')
const goal = ref<LevelGoal>('general')

function onSubmit(submittedText: string, submittedGoal: LevelGoal) {
  check(submittedText, submittedGoal)
  send('tool_form_submit', { tool: 'level' })
}

useSeoMeta({
  title: 'AI English Level Checker — estimate your CEFR band (A1–C2)',
  description:
    'Free AI English level checker. Paste 100–500 words and get an estimated CEFR band (A1–C2), sub-scores, and a 7-day plan. Works as a writing level checker, English proficiency checker, and CEFR level checker — no signup required.',
  ogTitle: 'AI English Level Checker — estimate your CEFR band',
  ogDescription:
    'Free AI English level checker. Estimate your CEFR range from your own writing. Sub-scores, three priorities, a 7-day plan. Also works as a writing level checker and English proficiency checker.',
  ogImage: `${config.public.siteUrl}/og-image.svg`,
  ogUrl: `${config.public.siteUrl}/english-level-checker`,
  twitterTitle: 'AI English Level Checker',
  twitterDescription:
    'Estimate your CEFR range from your own writing. Sub-scores, three priorities, a 7-day plan.',
  twitterImage: `${config.public.siteUrl}/og-image.svg`,
  twitterCard: 'summary_large_image',
  canonical: `${config.public.siteUrl}/english-level-checker`,
})

useHead({
  link: [{ rel: 'canonical', href: `${config.public.siteUrl}/english-level-checker` }],
  script: [
    {
      type: 'application/ld+json',
      innerHTML: JSON.stringify({
        '@context': 'https://schema.org',
        '@type': 'WebApplication',
        name: 'AI English Level Checker',
        url: `${config.public.siteUrl}/english-level-checker`,
        applicationCategory: 'EducationalApplication',
        operatingSystem: 'Any',
        browserRequirements: 'Requires JavaScript',
        inLanguage: 'en',
        description:
          'Free AI English level checker. Estimates a CEFR band (A1–C2) from a 100–500 word writing sample. Returns sub-scores, three priorities, and a 7-day plan. Also works as a writing level checker and English proficiency checker.',
        offers: {
          '@type': 'Offer',
          price: 0,
          priceCurrency: 'USD',
          availability: 'https://schema.org/InStock',
        },
        breadcrumb: {
          '@type': 'BreadcrumbList',
          itemListElement: [
            { '@type': 'ListItem', position: 1, name: 'Home', item: `${config.public.siteUrl}` },
            { '@type': 'ListItem', position: 2, name: 'English Level Checker', item: `${config.public.siteUrl}/english-level-checker` },
          ],
        },
      }),
    },
  ],
})

definePageMeta({
  title: 'AI English Level Checker',
})

const faqs = [
  {
    q: 'How does this AI English level checker work?',
    a: 'Paste 100–500 words of your own writing. The checker analyses sentence complexity, vocabulary diversity, grammar patterns, and coherence, then estimates your CEFR range (A1–C2) with sub-scores and three priorities.',
  },
  {
    q: 'Is this an official CEFR level checker?',
    a: 'No. It is an AI-assisted estimate based on your writing sample. It is not an official CEFR, IELTS, TOEFL, or Cambridge certification. Use it as a starting point, not as a final judgment.',
  },
  {
    q: 'Can I use it as an English writing level checker?',
    a: 'Yes. The tool specifically analyses your writing, so it works well as a writing level checker. It is most accurate when you paste something you wrote yourself, not a textbook excerpt.',
  },
  {
    q: 'Is this an English proficiency checker?',
    a: 'It gives you an estimate of your English proficiency based on writing. For a full proficiency picture, combine it with speaking and listening assessments.',
  },
  {
    q: 'Can I check my English level AI-style for free?',
    a: 'Yes. The tool is free, requires no signup, and gives an instant AI-based estimate. There may be a daily cap during launch to keep the service available.',
  },
  {
    q: 'What is the difference between this and an English level test online?',
    a: 'Traditional English level tests use fixed multiple-choice questions. This checker analyses your actual writing, which gives a more realistic picture of how you use English in practice.',
  },
  {
    q: 'Does it generate an English study plan?',
    a: 'The result includes three priorities and a 7-day starter plan. For a longer roadmap, you can use the output as input to an English study plan generator.',
  },
]
</script>